version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/ruby:2.4.0 # ...with this image as the primary container; this is where all `steps` will run
        environment: # environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_VERSION: 1.15.1
          RAILS_ENV: test

    working_directory: ~/circleci_demo # directory where steps will run

    steps: # a collection of executable commands
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
