version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.2.5
    environment:
      BUNDLE_VERSION: 1.15.1
    working_directory: ~/circleci_demo
    steps:
      - checkout
      - run:
        - name: 'Database setup'
        - command:
          - bundle exec rake db:schema:load RAILS_ENV=test
          - bundle exec rake db:create RAILS_ENV=production
      - run:
        - name: 'Precompile Assets'
        - command:
          - bundle exec rake assets:precompile RAILS_ENV=production
